use std::{
    cell::{Cell, RefCell},
    ffi::c_void,
    future::Future,
    pin::Pin,
    rc::Rc,
    task::{Context, Poll, Waker},
    thread::LocalKey,
};

pub use wasm_split_macro::{lazy_loader, wasm_split};

pub type Result<T> = std::result::Result<T, SplitLoaderError>;

#[non_exhaustive]
#[derive(Debug, Clone)]
pub enum SplitLoaderError {
    FailedToLoad,
}
impl std::fmt::Display for SplitLoaderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SplitLoaderError::FailedToLoad => write!(f, "Failed to load wasm-split module"),
        }
    }
}

impl std::error::Error for SplitLoaderError {}

/// A lazy loader that can be used to load a function from a split out `.wasm` file.
///
/// # Example
///
/// To use the split loader, you must first create the loader using the `lazy_loader` macro. This macro
/// requires the complete signature of the function you want to load. The extern abi string denotes
/// which module the function should be loaded from. If you don't know which module to use, use `auto`
/// and wasm-split will automatically combine all the modules into one.
///
/// ```rust, ignore
/// static LOADER: wasm_split::LazyLoader<Args, Ret> = wasm_split::lazy_loader!(extern "auto" fn SomeFunction(args: Args) -> Ret);
///
/// fn SomeFunction(args: Args) -> Ret {
///     // Implementation
/// }
/// ```
///
/// ## The `#[component(lazy)]` macro
///
/// If you're using wasm-split with Dioxus, the `#[component(lazy)]` macro is provided that wraps
/// the lazy loader with suspense. This means that the component will suspense until its body has
/// been loaded.
///
/// ```rust, ignore
/// fn app() -> Element {
///     rsx! {
///         Suspense {
///             fallback: rsx! { "Loading..." },
///             LazyComponent { abc: 0 }
///         }
///     }
/// }
///
/// #[component(lazy)]
/// fn LazyComponent(abc: i32) -> Element {
///     rsx! {
///         div {
///             "This is a lazy component! {abc}"
///         }
///     }
/// }
/// ```
pub struct LazyLoader<Args, Ret> {
    imported: unsafe extern "C" fn(arg: Args) -> Ret,
    key: &'static LocalKey<LazySplitLoader>,
}

impl<Args, Ret> LazyLoader<Args, Ret> {
    /// Create a new lazy loader from a lazy imported function and a LazySplitLoader
    ///
    /// # Safety
    /// This is unsafe because we're taking an arbitrary function pointer and using it as the loader.
    /// This function is likely not instantiated when passed here, so it should never be called directly.
    #[doc(hidden)]
    pub const unsafe fn new(
        imported: unsafe extern "C" fn(arg: Args) -> Ret,
        key: &'static LocalKey<LazySplitLoader>,
    ) -> Self {
        Self { imported, key }
    }

    /// Create a new lazy loader that is already resolved.
    pub const fn preloaded(f: fn(Args) -> Ret) -> Self {
        let imported =
            unsafe { std::mem::transmute::<fn(Args) -> Ret, unsafe extern "C" fn(Args) -> Ret>(f) };

        thread_local! {
            static LAZY: LazySplitLoader = LazySplitLoader::preloaded();
        };

        Self {
            imported,
            key: &LAZY,
        }
    }

    /// Load the module. Resolves `true` once it is loaded; `false` if this attempt failed, in
    /// which case a later call tries again.
    pub async fn load(&'static self) -> bool {
        self.key.with(|inner| inner.load()).await
    }

    /// Whether the module has finished loading, so [`LazyLoader::call`] succeeds without waiting.
    pub fn is_loaded(&'static self) -> bool {
        self.key.with(|inner| inner.loader.loaded.get())
    }

    /// Call the lazy loader with the given arguments
    pub fn call(&'static self, args: Args) -> Result<Ret> {
        if !self.is_loaded() {
            return Err(SplitLoaderError::FailedToLoad);
        }

        Ok(unsafe { (self.imported)(args) })
    }
}

type LoadCallbackFn = unsafe extern "C" fn(*const c_void, bool) -> ();
type LoadFn = unsafe extern "C" fn(LoadCallbackFn, *const c_void) -> ();

/// Loads one split module. A failed attempt is not remembered: the next [`LazySplitLoader::load`]
/// starts a new one, so a network blip does not break the module for the rest of the page's life.
pub struct LazySplitLoader {
    loader: Rc<SplitLoader>,
}

impl LazySplitLoader {
    /// Create a new lazy split loader from a load function that is generated by the wasm-split macro
    ///
    /// # Safety
    ///
    /// This is unsafe because we're taking an arbitrary function pointer and using it as the loader.
    /// It is likely not instantiated when passed here, so it should never be called directly.
    #[doc(hidden)]
    pub unsafe fn new(load: LoadFn) -> Self {
        Self {
            loader: Rc::new(SplitLoader::new(Some(load), false)),
        }
    }

    fn preloaded() -> Self {
        Self {
            loader: Rc::new(SplitLoader::new(None, true)),
        }
    }

    fn load(&self) -> SplitLoaderFuture {
        SplitLoaderFuture {
            loader: self.loader.clone(),
            attempt: None,
        }
    }

    /// Wait for the lazy loader to load. `false` if this attempt failed.
    pub async fn ensure_loaded(loader: &'static std::thread::LocalKey<LazySplitLoader>) -> bool {
        loader.with(|inner| inner.load()).await
    }
}

struct SplitLoader {
    load: Option<LoadFn>,
    loaded: Cell<bool>,
    /// Number of the attempt in flight, or of the last one that finished.
    attempt: Cell<u64>,
    in_flight: Cell<bool>,
    wakers: RefCell<Vec<Waker>>,
}

impl SplitLoader {
    fn new(load: Option<LoadFn>, loaded: bool) -> Self {
        Self {
            load,
            loaded: Cell::new(loaded),
            attempt: Cell::new(0),
            in_flight: Cell::new(false),
            wakers: RefCell::new(Vec::new()),
        }
    }

    fn finish(&self, success: bool) {
        self.in_flight.set(false);
        if success {
            self.loaded.set(true);
        }
        for waker in self.wakers.take() {
            waker.wake();
        }
    }
}

/// Waits on one load attempt, joining the one in flight or starting a new one.
struct SplitLoaderFuture {
    loader: Rc<SplitLoader>,
    attempt: Option<u64>,
}

impl Future for SplitLoaderFuture {
    type Output = bool;

    fn poll(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<bool> {
        unsafe extern "C" fn load_callback(loader: *const c_void, success: bool) {
            let loader = unsafe { Rc::from_raw(loader as *const SplitLoader) };
            loader.finish(success);
        }

        let loader = self.loader.clone();
        if loader.loaded.get() {
            return Poll::Ready(true);
        }

        match self.attempt {
            // The attempt this future joined has finished without loading the module.
            Some(attempt) if !loader.in_flight.get() || loader.attempt.get() != attempt => {
                Poll::Ready(false)
            }
            Some(_) => {
                loader.wakers.borrow_mut().push(cx.waker().clone());
                Poll::Pending
            }
            None => {
                loader.wakers.borrow_mut().push(cx.waker().clone());
                if !loader.in_flight.get() {
                    let Some(load) = loader.load else {
                        return Poll::Ready(false);
                    };
                    loader.attempt.set(loader.attempt.get() + 1);
                    loader.in_flight.set(true);
                    unsafe {
                        load(
                            load_callback,
                            Rc::<SplitLoader>::into_raw(loader.clone()) as *const c_void,
                        )
                    };
                }
                self.attempt = Some(loader.attempt.get());
                if loader.loaded.get() {
                    // The callback ran synchronously.
                    return Poll::Ready(true);
                }
                if !loader.in_flight.get() {
                    return Poll::Ready(false);
                }
                Poll::Pending
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::task::Waker;

    thread_local! {
        static PENDING: Cell<Option<(LoadCallbackFn, *const c_void)>> = const { Cell::new(None) };
        static LOADS: Cell<u32> = const { Cell::new(0) };
    }

    unsafe extern "C" fn fake_load(callback: LoadCallbackFn, data: *const c_void) {
        LOADS.set(LOADS.get() + 1);
        PENDING.set(Some((callback, data)));
    }

    fn settle(success: bool) {
        let (callback, data) = PENDING.take().expect("a load is in flight");
        unsafe { callback(data, success) };
    }

    fn poll(future: &mut Pin<Box<SplitLoaderFuture>>) -> Poll<bool> {
        future
            .as_mut()
            .poll(&mut Context::from_waker(Waker::noop()))
    }

    #[test]
    fn a_failed_load_is_retried_by_the_next_caller() {
        let loader = unsafe { LazySplitLoader::new(fake_load) };

        let mut first = Box::pin(loader.load());
        let mut joined = Box::pin(loader.load());
        assert_eq!(poll(&mut first), Poll::Pending);
        assert_eq!(poll(&mut joined), Poll::Pending);
        assert_eq!(LOADS.get(), 1, "concurrent callers share one attempt");

        settle(false);
        assert_eq!(poll(&mut first), Poll::Ready(false));
        assert_eq!(poll(&mut joined), Poll::Ready(false));

        let mut retry = Box::pin(loader.load());
        assert_eq!(poll(&mut retry), Poll::Pending);
        assert_eq!(LOADS.get(), 2, "the failure was not memoized");
        settle(true);
        assert_eq!(poll(&mut retry), Poll::Ready(true));
        assert_eq!(poll(&mut Box::pin(loader.load())), Poll::Ready(true));
        assert_eq!(LOADS.get(), 2);
    }
}
